---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-networkpolicy
  annotations:
    policies.kyverno.io/title: Add Network Policy
    policies.kyverno.io/category: Multi-Tenancy
    policies.kyverno.io/description: >-
      By default, Kubernetes allows communications across all pods within a cluster. 
      Network policies and, a CNI that supports network policies, must be used to restrict 
      communications. A default NetworkPolicy should be configured for each namespace to 
      default deny all ingress and egress traffic to the pods in the namespace. Application 
      teams can then configure additional NetworkPolicy resources to allow desired traffic 
      to application pods from select sources.
spec:
  validationFailureAction: audit
  rules:
  - name: default-deny
    match:
      resources: 
        kinds:
        - Namespace
        name: "*"
    exclude:
      resources:
        namespaces:
        - "kube-system"
        - "default"
        - "kube-public"
        - "kyverno"
    generate:
      kind: NetworkPolicy
      name: default-deny
      namespace: "{{request.object.metadata.name}}"
      data:
        spec:
          # select all pods in the namespace
          podSelector: {}
          # deny all traffic
          policyTypes: 
          - Ingress
          - Egress
  - name: exclude-dns
    match:
      resources:
        kinds:
        - Namespace
        name: "*"
    exclude:
      resources:
        namespaces:
        - "kube-system"
        - "default"
        - "kube-public"
        - "kyverno"
    generate:
      kind: NetworkPolicy
      name: allow-to-dns
      namespace: "{{request.object.metadata.name}}"
      data:
        spec:
          # select all pods in the namespace
          podSelector: {}
          policyTypes: 
          - Egress
          egress:
          - to:
            - namespaceSelector:
                matchLabels:
                  networking/namespace: kube-system
              podSelector:
                matchLabels:
                  k8s-app: kube-dns
            ports:
            - protocol: TCP
              port: 53
            - protocol: UDP
              port: 53
  - name: exclude-from-ingress
    match:
      resources:
        kinds:
        - Namespace
        name: "*"
    exclude:
      resources:
        namespaces:
        - "kube-system"
        - "default"
        - "kube-public"
        - "kyverno"
    generate:
      kind: NetworkPolicy
      name: allow-from-ingress
      namespace: "{{request.object.metadata.name}}"
      data:
        spec:
          # select all pods in the namespace
          podSelector: {}
          policyTypes:
          - Ingress
          ingress:
          - from:
            - namespaceSelector:
                matchLabels:
                  networking/namespace: ingress

